### PR TITLE
build: use esbuild to generate layer

### PR DESCRIPTION
**Pull request by pragmaticivan**
## Before:

Screenshot 2024-11-20 at 12 44 35 PM

Screenshot 2024-11-20 at 12 45 32 PM

## After:

Screenshot 2024-11-20 at 12 44 05 PM

Screenshot 2024-11-20 at 12 46 24 PM

### CODE REVIEW

**Comment by pragmaticivan** [comment]
I might need some help testing this with an alpha layer for the esm module resolution

**Comment by pragmaticivan** [comment]
It turns out that for ESM, will still need the `import-in-the-middle` and I the optional source maps are also missing here, although they are optional, so will only be included if the user pass a nodejs flag.

**Comment by pragmaticivan** [comment]
Screenshot 2024-12-04 at 5 18 49 PM

New Layer Size: 

Some files are not included in the runtime.

**Comment by pragmaticivan** [comment]
Closing this one for some live tests with ESM first

**Comment by tylerbenson** [comment]
Worth revisiting?

**Comment by pragmaticivan** [comment]
@serkan-ozal was workign on a different trial with webpack instead

**Pull request closed without merging**
