### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by ankur0904**
Fixed typo
`recievers -> receivers`

### CODE REVIEW

**Review by tylerbenson — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Thanks @ankur0904, please sign the CLA and we can get this merged!

**Comment by ankur0904** [comment]
@codeboten @tylerbenson Done.

**Review by codeboten — APPROVED** [review]
Thanks!

**Comment by ankur0904** [comment]
@codeboten Thanks :)

**Pull request merged**
