### PR TITLE
feat(nodejs): add logger sdk, fix metrics and update some packages

### LINKED ISSUE #1458: Support sdk-logs for nodejs lambda wrapper
**Is your feature request related to a problem? Please describe.**
Hi there, in addition to metrics and traces, I would also like to send logs via https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/sdk-logs

**Describe the solution you'd like**
Just add support for that, since the collector can deal with that now.

**Describe alternatives you've considered**
Instrument logs manually and send to the same collector.

### PR DESCRIPTION
**Pull request by pragmaticivan**
fixes #1458

### CODE REVIEW

**Comment by martinkuba** [comment]
It looks to me like the `sdk-logs` package is missing in the package.json file.

**Comment by pragmaticivan** [comment]
> It looks to me like the `sdk-logs` package is missing in the package.json file.

Good catch @martinkuba , just realized one my changes didn't go through

**Comment by pragmaticivan** [comment]
Hi @martinkuba @tylerbenson is there a way to release an alpha version of this layer for some manual tests?

**Comment by tylerbenson** [comment]
I'm not sure what the process is, but I believe you can publish the layer to your own account and test from there.

**Comment by pragmaticivan** [comment]
I have this working on my own account for Metrics and Tracing already, checking logs

**Comment by pragmaticivan** [comment]
Screenshot 2024-08-09 at 11 23 42 AM
Screenshot 2024-08-09 at 11 23 48 AM
Screenshot 2024-08-09 at 11 24 06 AM
Screenshot 2024-08-09 at 11 25 03 AM

I now have Logs, Tracing, Metrics, and Tracing correlation with Logs working!

**Comment by pragmaticivan** [comment]
Log code:

```ts
const otelLogger = logsAPI.logs.getLogger('default');
  otelLogger.emit({
    severityNumber: logsAPI.SeverityNumber.INFO,
    severityText: 'INFO',
    body: 'this is a log record body - test on new build',
    attributes: { 'log.type': 'LogRecord' },
  });
```

**Comment by pragmaticivan** [comment]
Screenshot 2024-08-09 at 3 22 22 PM

Also tested producing logs with Winston Transport

**Review by tylerbenson — APPROVED** [review]

**Comment by pragmaticivan** [comment]
👋🏽 @tylerbenson do you think we can release this change this week?

**Comment by pragmaticivan** [comment]
Hi @tylerbenson mind approving the last merge test run? there was a conflict with the other PR merged yesterday

**Comment by serkan-ozal** [comment]
LGTM! 

One question: Does enabling logging exporter mean that console log methods (log, trace, debug, info, error, ...) are automatically patched/wrapped and all console logs are exported by default?

**Comment by pragmaticivan** [comment]
@serkan-ozal no, your own lib has to be compatible with the OTEL SPEC, `OR` you have to manually emit logs using the OTEL Logs API:

```
const otelLogger = logsAPI.logs.getLogger('default');
  otelLogger.emit({
    severityNumber: logsAPI.SeverityNumber.INFO,
    severityText: 'INFO',
    body: 'this is a log record body - test on new build',
    attributes: { 'log.type': 'LogRecord' },
  });
```

In my example, my project was using winston, so I just had to add https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/winston-transport so that my existing logging lib can also emit otel resources automatically

**Review by serkan-ozal — APPROVED** [review]

**Pull request merged**
