### PR TITLE
[chore]  Update Python Dependencies and remove unsued scripts in the repo

### LINKED ISSUE #643: Remove Terraform Integration test script
**Describe the bug**
The Integration-tests scripts that exists in this repo are currently not used. but these scripts are used in in the [aws-otel-lambda](https://github.com/aws-observability/aws-otel-lambda) distribution for the integration testing, the aws-otel-lambda use this whole repo as a sub module. This issue is created to bring this discussion into light whether to port over this script to aws-otel-lambda repo completely or determine if these scripts can be used for integ tests for this repo.

### PR DESCRIPTION
**Pull request by vasireddy99**
Fixes #643 

Thi PR removes the integration test scripts in the repo, which are not used and have no purpose to sit in this repo, helps for the better maintainance of the project and Updates the Python dependencies.

### CODE REVIEW

**Review by shuwpan — APPROVED** [review]
Looks legit to me

**Review by codeboten — COMMENTED** [review]
Please split the two into separate PRs, otherwise it makes it harder to review

**Comment by vasireddy99** [comment]
> Please split the two into separate PRs, otherwise it makes it harder to review

I Was initially doing in two PRs but, the PR build was failing, if not updating the version of python. So had to keep it in one PR.

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
Looks like there's an error in the build:

```
Error: CustomMakeBuilder:MakeBuild - Make Failed: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by vasireddy99** [comment]
> Looks like there's an error in the build:
> 
> ```
> Error: CustomMakeBuilder:MakeBuild - Make Failed: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> ```

yeah looks like the [failure](https://github.com/open-telemetry/opentelemetry-lambda/actions/runs/5138251521/jobs/9247371979?pr=717#step:6:199) is something related to this [change](https://github.com/open-telemetry/opentelemetry-lambda/pull/732/files) looking into it now.

**Comment by vasireddy99** [comment]
> Looks like there's an error in the build:
> 
> ```
> Error: CustomMakeBuilder:MakeBuild - Make Failed: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> ```

oh yes, Rebasing to the main has worked as it seems git merge has both changes in place led to conflict. 

The PR is now ready to merge :-).

**Comment by codeboten** [comment]
Thanks @vasireddy99

**Pull request merged**
