### PR TITLE
Add fast startup option for Java agent by enabling JIT tiered compilation to stop at level 1 …

### PR DESCRIPTION
**Pull request by serkan-ozal**
… and disabling bytecode verification.

Fast startup mode is disabled by default but can be enabled by setting `OTEL_JAVA_AGENT_FAST_STARTUP_ENABLED`
 environment variable to `true`.

For more information about the idea behind this optimization, you can check the following resources:
- https://aws.amazon.com/tr/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
- https://aws.amazon.com/tr/blogs/compute/increasing-performance-of-java-aws-lambda-functions-using-tiered-compilation/

Here are some coldstart (init duration) numbers (I have tested with simple hello world Lambda function which does nothing other than printing hello world):

## Memory Size: 3072 MB
| Configuration                                       | Init Duration (ms)   |
| ------------------------------------ | ------------------: |
| No Agent                                              |                          379 |
| With Agent                                           |                       6384  |
| With Agent (Fast startup enabled)    |                       2590  |

When fast startup enabled, Lambda function starts **2.46x** faster.

## Memory Size: 2048 MB
| Configuration                                       | Init Duration (ms)   |
| ------------------------------------ | ------------------: |
| No Agent                                              |                          448 |
| With Agent                                           |                       8819  |
| With Agent (Fast startup enabled)    |                       2907  |

When fast startup enabled, Lambda function starts **3.03x** faster.

## Memory Size: 1536 MB
| Configuration                                       | Init Duration (ms)   |
| ------------------------------------ | ------------------: |
| No Agent                                              |                          500 |
| With Agent                                           |  > 10000 (timeout) |
| With Agent (Fast startup enabled)    |                       3492  |

## Memory Size: 1024 MB
| Configuration                                       | Init Duration (ms)   |
| ------------------------------------ | ------------------: |
| No Agent                                              |                          503 |
| With Agent                                           |  > 10000 (timeout) |
| With Agent (Fast startup enabled)    |                       3500  |

### CODE REVIEW

**Review by tylerbenson — APPROVED** [review]
Thanks for the contribution.  This definitely looks like an interesting option for lambdas that are short lived.

**Comment by tylerbenson** [comment]
One request... Would you please update [the readme](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/java/README.md) with some documentation so this new setting is discoverable and users can understand what it does?

**Comment by serkan-ozal** [comment]
@tylerbenson Just updated the README with this new option.

**Comment by serkan-ozal** [comment]
Thanks for merging @tylerbenson.
When are you planning to release new Java agent layer with this addition?

**Comment by tylerbenson** [comment]
We are overdue... I can try to do a release this week.

**Pull request merged**
