### PR TITLE
Add secretsmanager confmap provider

### PR DESCRIPTION
**Pull request by hkarn-godaddy**
This PR adds [secretsmanagerprovider](https://github.com/hkarn-godaddy/opentelemetry-collector-contrib/tree/main/confmap/provider/secretsmanagerprovider) confmap provider from [opentelemetry-collector-contrib](https://github.com/hkarn-godaddy/opentelemetry-collector-contrib) repo.

### CODE REVIEW

**Review by tylerbenson — APPROVED** [review]

**Review by nslaughter — APPROVED** [review]

**Comment by rapphil** [comment]
I initially thought that it would be possible to use environment variables and some integration between lambda and secrets manager, but it seems that it is not possible and maybe it does not make sense because env vars values don't dynamically update across invocations, having said that I think it makes sense to include this confmap provider here.

Not a blocker for this pr, but one thing that I wanted to understand is how much these confmap providers that require fetching the configuration from a remote place add to the cold start time. 

LGTM! thanks!

**Review by rapphil — APPROVED** [review]

**Comment by hkarn-godaddy** [comment]
Resolved conflicts.

**Comment by hkarn-godaddy** [comment]
@tylerbenson can we get this pull request merged?

**Comment by tylerbenson** [comment]
@hkarn-godaddy sorry.  One last rebase please and I'll get it merged.

**Comment by hkarn-godaddy** [comment]
PR updated.

**Pull request merged**
